### ISSUE TITLE
Fix Computation Breaking when selecting `Electricity, at consumer`

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-webapp#14]
...presumably because this process is relevant when building the dataframes displayed with the `tabular` widget.

```
2024-09-15 11:26:50,990 error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'type': 'event', 'name': 'button_click', 'values': {'type': 'map', 'entries': [['model', {'id': 'p21725'}]]}}}]} 
 error: KeyError('[0] not found in axis')
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/server/protocol_handler.py", line 94, in handle
    work = await handler(message, connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/server/session.py", line 94, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/server/session.py", line 286, in _handle_patch
    message.apply_to_document(self.document, self)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 453, in invoke_with_curdoc
    return f()
           ^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/document.py", line 391, in apply_json_patch
    DocumentPatchedEvent.handle_event(self, event, setter)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/events.py", line 244, in handle_event
    event_cls._handle_event(doc, event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/events.py", line 279, in _handle_event
    cb(event.msg_data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 400, in trigger_event
    model._trigger_event(event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 111, in _trigger_event
    self.document.callbacks.notify_event(cast(Model, self), event, invoke)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 262, in notify_event
    invoke_with_curdoc(doc, callback_invoker)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/document/callbacks.py", line 453, in invoke_with_curdoc
    return f()
           ^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/bokeh/util/callback_manager.py", line 107, in invoke
    cast(EventCallbackWithEvent, callback)(event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/reactive.py", line 572, in _server_event
    self._comm_event(doc, event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/reactive.py", line 559, in _comm_event
    state._handle_exception(e)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/io/state.py", line 464, in _handle_exception
    raise exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/reactive.py", line 557, in _comm_event
    self._process_bokeh_event(doc, event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/reactive.py", line 494, in _process_bokeh_event
    self._process_event(event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/panel/widgets/button.py", line 242, in _process_event
    self.clicks += 1
    ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 528, in _f
    instance_param.__set__(obj, val)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 530, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameters.py", line 543, in __set__
    super().__set__(obj,val)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 530, in _f
    return f(self, obj, val)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 1552, in __set__
    obj.param._call_watcher(watcher, event)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 2525, in _call_watcher
    self_._execute_watcher(watcher, (event,))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/param/parameterized.py", line 2505, in _execute_watcher
    watcher.fn(*args, **kwargs)
  File "/Users/michaelweinold/github/brightway-webapp/app/app.py", line 551, in button_action_scope_analysis
    perform_graph_traversal(event)
  File "/Users/michaelweinold/github/brightway-webapp/app/app.py", line 527, in perform_graph_traversal
    panel_lca_class_instance.perform_graph_traversal(event)
  File "/Users/michaelweinold/github/brightway-webapp/app/app.py", line 454, in perform_graph_traversal
    self.df_graph_traversal_edges: pd.DataFrame = edges_dict_to_dataframe(self.graph_traversal['edges'])
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/michaelweinold/github/brightway-webapp/app/app.py", line 116, in edges_dict_to_dataframe
    return pd.DataFrame(list_of_row_dicts).drop(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/panel_dev_macos/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: '[0] not found in axis'
```

**Comment by michaelweinold** [comment]
...this problem is not specific to electricity. Instead, the error occurs when there are no nodes in the dataframe - meaning that the graph traversal at a set cut-off did not return any relevant upstream nodes.
