### ISSUE TITLE
ValueError: Requested 'bw2data>=4.0.dev57', but bw2data==4.0.dev52 is already installed

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-webapp#21]
This does not negatively affect execution, but should still be resolved:

```
[Log] PythonError: Traceback (most recent call last): (index.js, line 33)
  File "/lib/python312.zip/_pyodide/_base.py", line 596, in eval_code_async
    await CodeRunner(
  File "/lib/python312.zip/_pyodide/_base.py", line 412, in run_async
    await coroutine
  File "<exec>", line 3, in <module>
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 198, in _add_requirement_from_package_index
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 236, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 59, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 198, in _add_requirement_from_package_index
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 236, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 59, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 141, in add_requirement_inner
    satisfied, ver = self.check_version_satisfied(req)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 86, in check_version_satisfied
    raise ValueError(
ValueError: Requested 'bw2data>=4.0.dev57', but bw2data==4.0.dev52 is already installed
```

**Comment by michaelweinold** [comment]
That's the pin of `multifunctional` (excerpt from `johnnydep bw2io==0.9.dev37`:

```
│   ├── multifunctional>=0.7.1                                Code for handling multifunctional activities in Brightway
│   │   ├── blinker                                           Fast, simple object-to-object and broadcast signaling
│   │   ├── bw-processing>=0.9.6                              Foo
│   │   │   ├── fsspec                                        File-system specification
│   │   │   ├── morefs                                        A collection of self-contained fsspec-based filesystems
│   │   │   │   └── fsspec                                    File-system specification
│   │   │   ├── numpy                                         Fundamental package for array computing in Python
│   │   │   └── pandas                                        Powerful data structures for data analysis, time series, and statistics
│   │   │       ├── numpy>=1.22.4                             Fundamental package for array computing in Python
│   │   │       ├── python-dateutil>=2.8.2                    Extensions to the standard Python datetime module
│   │   │       │   └── six>=1.5                              Python 2 and 3 compatibility utilities
│   │   │       ├── pytz>=2020.1                              World timezone definitions, modern and historical
│   │   │       └── tzdata>=2022.7                            Provider of IANA time zone data
│   │   ├── bw2data>=4.0.dev57                                Tools for the management of inventory databases and impact assessment methods. Part of the Brightway LCA framework.
```
